# new exception type
class NetworkError(Exception):
    pass
